### ISSUE TITLE
change where Exposure class is created

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#129]
This horrible logic of setting up scan.md items then running RE then unsetting them is a strong indication that we have the wrong design, and brings back bad memories of when we were trying to do this with gs.RE (do you remember that! :)

Actually what is wrong is that these medata items are not ScanPlan attributes, they are Scan attributes. or perhaps Exposure attributes.  If we set them at the right level, we should never have to unset them later.  We create an Exposure instance inside _get_light_images.  Perhaps we either need a Scan object in prun or to create the Exposre instance in prun and pass it down.

**Comment by chiahaoliu** [comment]
:+1:

**Comment by chiahaoliu** [comment]
after meeting, we both agree on calling this `Exposure` class mentioned here as `Scan` class, since we don't really have access to information at exposure level ( mostly are machine readback values)

`Scan` class will be created in `beamtime.py`. It inherits metadata from`ScanPlan` and `Sample`. One thing definitely wanted inside is like `Scan.md = Union(ScanPlan.md, Sample.md)`. Detailed
