### ISSUE TITLE
bluesky scanplan in scans list

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#183]
I am not sure if hte bluesky passthrough scanplan is ready or not, but if it is, it should be included in the  quickstart list of scans.

**Comment by chiahaoliu** [comment]
bluesky passthrough plan would require our ``ScanPlan`` to inherit from bluesky Scan base, so that ``prun`` can take arbitrary scan, either from us or from bluesky (now we are calling certain bluesky plan in ``ScanPlan``) . I showed a prototype of this inherit scan and new ``prun`` last Friday, and we both think this major refactoring should happen after API has been widely accepted by users.

**Comment by sbillinge** [comment]
just to check, this is not possible before the major refactor?

On Tue, May 17, 2016 at 11:13 AM, Timothy Liu <notifications@github.com>
wrote:

> bluesky passthrough plan would require our ScanPlan to inherit from
> bluesky Scan base, so that prun can take arbitrary scan, either from us
> or from bluesky (now we are calling certain bluesky plan in ScanPlan) . I
> showed a prototype of this inherit scan and new prun last Friday, and we
> both think this major refactoring should happen after API has been widely
> accepted by users.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/183#issuecomment-219749836>
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
Under current architecture, it will be pretty messy. In order to allow it, we need to monkey patch enitre code but metadata won't be as rich as it should be.

The main reason is ``prun`` doesn't call RunEngine directly, instead, it calls ``_unpack_and_run`` to parse information passed down with ScanPlan and Sample objects and ``_unpack_and_run`` calls ``get_light_image``, ``collect_time_series`` ...e.t.c. based on keyword arguments given. Layers between ``prun`` make taking arbitrary  bluesky scan and extracting metadata challenging.

**Comment by sbillinge** [comment]
Let's think if there is an easy way to do it so the functionality is there
even if no md is saved at all.

S

On Tuesday, May 17, 2016, Timothy Liu <notifications@github.com> wrote:

> Under current architecture, it will be pretty messy. In order to allow it,
> we need to monkey patch enitre code but metadata won't be as rich as it
> should be.
>
> The main reason is prun doesn't call RunEngine directly, instead, it
> calls _unpack_and_run to parse information passed down with ScanPlan and
> Sample objects and _unpack_and_run calls get_light_image,
> collect_time_series ...e.t.c. based on keyword arguments given. Layers
> between prun make taking arbitrary bluesky scan and extracting metadata
> challenging.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/183#issuecomment-219848107>
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
functionality is included in code and for documented in the current github page.
