### ISSUE TITLE
opyhd object is not serializable

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#196]
Current API with arbitrary ``bluesky`` plan is:
````
cc = Count([pe1c, em], 10)
ScanPlan('bluesky', {'bluesky_plan': cc})
# we have yaml.dump(....) method inside ScanPlan
````
Ideally, we would have to yamlize opyhd objects (they are passed into scanplan directly). However ophyd objects are not serializble at this point. 

After playing it over the weekend, I am thinking for this cycle, the most possible walkaround is:
For arbitrary bluesky plan, we only yamlize reference to its memory location. Even though this reference is only valid for current iPython session, we at least can save md up to ScanPlan level and make arbitrary bluesky possible within xpdAcq framework. 

@sbillinge  Does it sound like a good idea?

Here is some example with id
````
In [20]: aa = Count([det],5)
In [21]: id(aa)
Out[21]: 4513426120

# recovery 
In [23]: pp = ctypes.cast(id(aa), ctypes.py_object).value
In [24]: pp == aa
Out[24]: True

````

**Comment by sbillinge** [comment]
This doesn't make any sense to me since the only point of yamelizing things is so the objects can be reloaded after a crash.  For this release we can do one of two things.  Either not bother yamifying at all, and warn users of this behavior, or come up with a way of simply saving the code for the bs Plan definition, so it can be cut and pasted again and reinstantiated after recovery.

Workflow would be:
1) user defines a bs Plan by writing code, calling it ``mbsplan``
2) software saves code somehow
3) user makes ScanPlan that is a bs-passthrough of this Plan called ``mybspassthrough``
4) software yamifies, the ``mybspassthrough`` which saves the reference to the object name ``mbsplan``
5) software crashes
6) user restarts collection
7) user tries to use the yamified ``mybspassthrough``
8) software throws exception because it cannot find a bs Plan object called ``mybsplan``
9) software mentions to use that they should instantiate that Plan object first, but if it was instantiated in a previous icollection session, gives instructions how to find the code and rerun it 
10) user reruns the code to instantiate that plan

no idea how this can be done, but this behavior would be acceptable.

it is a bit complicated, maybe we should go with solution (a) [not support serialization for bs passthrough]  

Do you know if there are plans to make bs objects serializable?  How is bluesky project planning for the collection crashes....?

**Comment by chiahaoliu** [comment]
I already brought this point (make bs object serializable) to the software team. I think they are aware of it, just not ready yet.

Saving the code seems to be the solution at this point (that is also the suggestion I got from software team). However, it only works only up to object level. we can user ``repr`` and ``eval`` to transform object and its canonical strings back and forth, but not for the instance of bluesky plan ( and ``pe1c`` doesn't work either as it has special plugins...)

I tried to implement workflow listed above and each step is manageable, except for step 2) program saves code somehow. Yamlize objects seems to be necessary because now people at XPD are really used to ``bt.get()`` and ``bt.list()`` workflow. Is there any suggestion on that?

**Comment by sbillinge** [comment]
Saving the code so that users can cut and paste and rerun themselves is
fine, though I don't have a good way of doing it.  If there is not a good
way to do it then we should just punt.  We have 80% of the functionality we
want and if they have to retype their bluesky plan after a collection crash
then they will appreciate our xpdAcq code even more where everything comes
back! :)

On Wednesday, June 1, 2016, Timothy Liu <notifications@github.com> wrote:

> I already brought this point (make bs object serializable) to the software
> team. I think they are aware of it, just not ready yet.
>
> Saving the code seems to be the solution at this point (that is also the
> suggestion I got from software team). However, it only works only up to
> object level. we can user repr and eval to transform object and its
> canonical strings back and forth, but not for the instance of bluesky plan
> ( and pe1c doesn't work either as it has special plugins...)
>
> I tried to implement workflow listed above and each step is manageable,
> except for step 2) program saves code somehow. Yamlize objects seems to be
> necessary because now people at XPD are really used to bt.get() and
> bt.list() workflow. Is there any suggestion on that?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/196#issuecomment-223054508>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEDrUYyWGwRAkSm6Yp1cJDj6qgUk0n_3ks5qHbfrgaJpZM4Iq9Fa>
> .
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbillinge** [comment]
See #253 which supercedes this one.  Closing.
