### ISSUE TITLE
make sure that Acq is not a dependency of An

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#216]

**Comment by chiahaoliu** [comment]
currently ``Acq`` is separated from ``An`` at package level, however *collection profile* imports ``An`` during startup so that integration and saving functionality can be used in collection environment(terminal). 

That was suggested by user, however if we can teach them to separate workflow, we can completely separate these two packages.

Also, current version of ``An`` is isolated from ``Acq`` too, it would depend on ``databroker``

**Comment by CJ-Wright** [comment]
We could test this by putting this up on Travis-CI, install it without installing Acq, then run the tests. If none fail then we are separate from Acq, else we can see via the traceback which functions depend on Acq and commence code surgery.

**Comment by chiahaoliu** [comment]
can travis cover cases introduced by ``ipython_profile``?
I think ``Acq`` is separate from ``An`` but happy to see a proof :p

**Comment by CJ-Wright** [comment]
I am going to move this issue over to the An side.
