### ISSUE TITLE
How to include a prebuild fit2D mask for integration.

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#285]
The geometry and pattern I have is little complicated. I would like to build my own mask. How can I implement this mask generated using Fit2D into xpdAcq for integration?

**Comment by CJ-Wright** [comment]
I would suggest loading the mask with [fabio](http://pythonhosted.org/fabio/api/modules.html#module-fabio.fit2dmaskimage) then trying to compress it and stuff it into the metadata (Note this may need to be flipped, if so we can write a wrapper so that the user doesn't deal with flipping problems). Can we do this on the An side? We already have an implementation of code which will allow us to us arbitrary masks.

**Comment by sbillinge** [comment]
in integrate (etc), as well as `mask_setting='default'`, `'None'` and `'auto'`, it would be nice if users could specify a list of mask-files.  if extension is `.npy` assume it is pyFai, if it is `.msk` assume it is Fit2D.  Logic is
1. set them all to the same bit-set (1 is good pixel)
2. sum all the masks
3. apply the summed mask

If they want an automask and a fit2D mask can we support ['myfile.msk', 'myotherone.npy','auto'].  This would give resultant mask = myfile+myotherone+auto-generated one.

In that case we should also offer ['myfile.msk', 'myotherone.npy','default']

**Comment by chiahaoliu** [comment]
for the record, this issue was open by @sghose by accidentally used my account left at XPD.

tag him here so that he can receive notification about this thread.

**Comment by CJ-Wright** [comment]
This issue might need to be moved to an.
