### ISSUE TITLE
MNT: reformat 999-load.py

### ISSUE THREAD

**Issue by st3107** [xpdAcq/xpdAcq#563]
Hi @chiahaoliu . I am reformating the code in xpdacq so that it can pass the flake8 check. I see that there is a "999-load.py" which includes a lot of "from ... import *" and this "999-load.py" is not used in any places in the package. I wonder what is the usage of the "999-load.py" and it is really necessary to do "import *"

**Comment by chiahaoliu** [comment]
@st3107 thanks for helping clean the code. 

`999-load.py` is used to configure necessary "states" used as part of `xpdacq` interface (like creating xrun, import scan plan etc) and it is supposed to be included as a part of ipython profile for experiment and simulation environment, although it is not directly used in the package. It would be ok to remove it from xpdacq, but I'd suggest we still keep it under version control somewhere as I can imagine it needs to be change accordingly to code changes in the future.

`import * ` was indeed not ideal. I guess  the imports from `xpdacq.xpdacq` could be limited to functions related to `CustomizedRunEngine`, the imports from `xpdacq.beamtime` can be limited to `ScanPlan` currently supported and the we only need to import `run_calibration` from `xpdacq.calib`. Although the final test might still need to done at beamline and simulation environment for those changes.

One more thing. The sequence of import statements does matter. It took us quite some time to organize the package so that circular imports are avoided.

**Comment by st3107** [comment]
Thank you, Tim. I will change the import all to the names of the function and class defiend in the module so that it will import all the objects but avoid importing the stuff from other modules.
