### ISSUE TITLE
[user_feedback] 2016.02.14

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#72]
After talk with Soham
1. Program should be able to pause scan while beam is dumped. Even better if program can automatically restart after beam is resumed.
2. Allowed user to add comments. We have this functionality but it doesn't work properly.

**Comment by sbillinge** [comment]
1. Is already possible in bluesky.  Look for "suspenders" in the
documentation.  We probably want PVSuspendFloor and select a PV that is
something like ring current, or intensity.  I think everyone will want this
behavior so we should have it as default, possibly with an override.
2. Previously it was not possible to update metadata after a scan was
started.  I don't know if this behavior is still true.   If that is the
problem we could have a workaround if we made a
``comment(sampleO,scanO,**kwargs)`` which ran a scan with all the same
uid's from an earlier scan but tagged it as iscomment=True and saved the
comment in the ``{'user_comment: 'string'}`` kwarg, sthg like that.

**Comment by chiahaoliu** [comment]
1) Thanks, I have looked it on github. I think if we know the PV name related to beam dump, we can implement it.  @tacaswell  is the usage like `PVSuspendBoolHigh(RE, PV_name)`

**Comment by sbillinge** [comment]
Ask sanjit for the best pv to use

On Sunday, February 14, 2016, Timothy Liu <notifications@github.com> wrote:

> 1) Thanks, I have looked it on github. I think if we know the PV name
> related to beam dump, we can implement it. @tacaswell
> <https://github.com/tacaswell> is the usage like PVSuspendBoolHigh(RE,
> PV_name)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184043451>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbillinge** [comment]
It could be a counter like beam current or a monitor detector.  Then it
would be the Floor suspender.  I doubt there is a Bool for this.

On Sunday, February 14, 2016, Simon Billinge <simon.billinge@gmail.com>
wrote:

> Ask sanjit for the best pv to use
>
> On Sunday, February 14, 2016, Timothy Liu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> 1) Thanks, I have looked it on github. I think if we know the PV name
>> related to beam dump, we can implement it. @tacaswell
>> <https://github.com/tacaswell> is the usage like PVSuspendBoolHigh(RE,
>> PV_name)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184043451>.
>>
>
>
> --
> Prof. Simon Billinge
> Applied Physics & Applied Mathematics
> Columbia University
> 500 West 120th Street
> Room 200 Mudd, MC 4701
> New York, NY 10027
> Tel: (212)-854-2918 (o) 851-7428 (lab)
>
> Condensed Matter Physics and Materials Science Dept.
> Brookhaven National Laboratory
> P.O. Box 5000
> Upton, NY 11973-5000
> (631)-344-5661
>
> email: sb2896 at columbia dot edu
> home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
>
>

-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbanerjee23** [comment]
We're learning some things from the frequent beam dumps all day. Some notes from discussions:

- Milinda asked Sanjit recently if he knew of a good PV that would track beam current, and neither of them think this is available yet. 
  - At x17a there was an ion chamber in the hutch, which was read by SPEC. This doesn't exist at XPD yet. Milinda feels the best solution would be to install an ion chamber in the hutch at XPD, and will get in touch with the controls group next week to get going on this.

In the meantime, I though I could track all the PVs on the 28IDA overview window, guessing that something further upstream would indicate a problem. My first guess was that any beam dump could be tracked by a bool for the front end shutter (wrong): 

- We've had three beam dumps since 2PM: All three showed "Operating Mode: Failure" on the controls update (beam current) window. Two of them lead to the front end shutters being disabled immediately. The current beam dump showed a "No Beam" message. This did lead to the front end shutter being disabled (shows red on overview schematic), but there was a latency of about 10-15 minutes. Then about an hour later, the controls window also shows "Shutters Disabled." Here are some pics of the overview map:

- Normal Operation Upstream PVs:
![normal_up](https://cloud.githubusercontent.com/assets/7819851/13039942/e6a23ef0-d373-11e5-9388-5d0f98a9a8fd.jpg)

- Dump Upstream PVs:
![dump_up](https://cloud.githubusercontent.com/assets/7819851/13039947/ed7a8e08-d373-11e5-87f3-bc8356fafb8c.jpg)

- Normal Operation Downstream PVs:
![normal_down](https://cloud.githubusercontent.com/assets/7819851/13039954/fb2e26c2-d373-11e5-80da-640d4477e4e0.jpg)

- Dump Downstream PVs:
![dump_down](https://cloud.githubusercontent.com/assets/7819851/13039961/0857a1fc-d374-11e5-8a60-bdc69a7a0ddb.jpg)

You can see the front end shutter status at the very right of the Upstream PV pictiures. But, the shutter status isn't a PV, so the easy(est) bool fix isn't there, and given this weird latency, it wouldn't be good anyway. I don't know if you guys can read the numbers on those PVs (nor do I know what TCG, CCG, and IP stand for), but looking through them a bit:

- TCG vals don't change
- Most IP values don't change, a few do, but very little
- CCG values are always changing:
  - The rel. change for all of them after a dump make sense intuitively: they decrease during failure mode, and go back up when the FOE shutters enabled 
  - None change by orders of magnitude
  - One (downstream PV) has a larger rel. change than the rest: "BS:WB"
    - CCG BS:WB < 7.5 e -9 (During Dump)
    - CCG BS:WB > 8.3 e -9 (Normal Op)

That's probably not enough (or right) for a definitive solution, but that behavior does seem to be consistent today. Naively, it seems strange to me that we wouldn't be able to find a PV upstream of the photon shutter that would let us know when there is a beam dump. Not sure why we should be limited to an ion chamber in the hutch to check this, but there's likely a good reason. 

As of now, for me this is the most error prone part of running ScanPlans. If a long scan is interrupted by a beam dump, we wouldn't want to redo the whole ramp, and unless it freezes at a convenient point near the end/beginning of a tseries plan, we need to redefine a scan object, which updates bt.list, which changes all indices for the other objects.

Let me know if anything is unclear.

**Comment by sbanerjee23** [comment]
Question: If we are absent for a beam dump during a long scan, is there an easy way to find out what the last image collected was that had counts?

Also, if we can get a max detector counts per acquisition, could that be used as a threshold to either continue the cryostream ramp and aquisition, or stop it? Even if the dark current is smoothly varying, it has a max counts orders of magnitude less than a light regardless of sample type. So, since we are using the fast shutter, could xpdAcq know that the beam is down simply from PE1 counts, bypassing any PV stuff?  

Sorry if this is overboard, getting worried about missing dumps during the night. Yea I said it.

**Comment by sbillinge** [comment]
It would certainly be possible to use a detector count PV for checking for
this, but would be harder to recover, we would have to dial back probably
two frames at least which is not the default Bluesky behavior so would
require a lot of programming logic that would be hard to write.  I would be
surprised if there is not a (synchrotron) beam current PV though.....is
there not?

S

On Mon, Feb 15, 2016 at 2:38 AM, Soham Banerjee <notifications@github.com>
wrote:

> Question: If we are absent for a beam dump during a long scan, is there an
> easy way to find out what the last image collected was that had counts?
>
> Also, if we can get a max detector counts per acquisition, could that be
> used as a threshold to either continue the cryostream ramp and aquisition,
> or stop it? Even if the dark current is smoothly varying, it has a max
> counts orders of magnitude less than a light regardless of sample type. So,
> since we are using the fast shutter, could xpdAcq know that the beam is
> down simply from PE1 counts, bypassing any PV stuff?
>
> Sorry if this is overboard, getting worried about missing dumps during the
> night. Yea I said it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184100195>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbanerjee23** [comment]
There must be right? I'll follow up with Milinda and Sanjit if that helps. This seems too simple to not already exist, but I only checked the overview map, I bet I can find it on some other epics window.

**Comment by danielballan** [comment]
> That's probably not enough (or right) for a definitive solution, but that behavior does seem to be consistent today.

In that case, type

```python
from bluesky.suspenders import PVSuspendFloor
PVSuspendFloor(RE, 'PV_HERE', 7.5e-9, resume_thresh=8.3e-9)
```

in the interactive session, or add it to the IPython profile. Relevant section of docs: http://nsls-ii.github.io/bluesky/state-machine.html#suspending

> Naively, it seems strange to me that we wouldn't be able to find a PV upstream of the photon shutter that would let us know when there is a beam dump. 

23ID has something set up for this. Assuming that beam dumps are experienced more or less uniformly around the ring, you can probably read from their value. Quoting from their beamline config:

```python3
ring_curr = EpicsSignal('XF:23ID-SR{}I-I', name='ring_curr')
```

> If a long scan is interrupted by a beam dump (as is the case today for every attempted measurement) we wouldn't want to redo the whole ramp, and unless it freezes at a convenient point near the end/beginning of a tseries plan, we need to redefine a scan object, which updates bt.list, which changes all indices for the other objects.

I'm not sure what "ScanPlan" does, but if it's built on `AbsScanPlan` or any bluesky step scan plan, a suspension or a user-initiated pause should cause it to rewind to the last step, not redo the entire scan. Example:

```python
RE(AbsScanPlan([pe1c], cs700, t1, t2, num_steps), **dict_of_metadata_from_bt)
```

> Question: If we are absent for a beam dump during a long scan, is there an easy way to find out what the last image collected was that had counts?

I think we agree that identifying the problem upstream is preferable, but there are two alternatives along the lines you suggest:

1. Add a callback that looks at `pe1_stats1_total` or `pe1_image` and, if it sees low counts, calls `RE.request_pause()`. This would of course *pause*, not suspend, so it would wait for the user before it could resume.

```python
def pause_on_low_counts(name, doc):
    if 'pe1_stats1_total' not in doc['data']:
        # this callback is not applicable to this event
        return
    total_counts = doc['data']['pe1_stats1_total']
    if total_counts < THRESH:
        RE.request_pause()

token = RE.subscribe('event', pause_on_low_counts)
# 'token' is an integer you can use to unsubscribe later: RE.unsubscribe(token)
```

2. Write your own suspender. All of the subtle code is in a base class. Unfortunately, that base class does assume that it is talking to a PV, but it would be easy to remove that part and write an EPICS-less suspender that watches something else -- a file, or a binary flag on the class that is flipped by some other process. Then, use the code above, but instead of calling `request_pause`, flip a binary flag that tells `_should_suspend` to start returning True. Wait ten minutes and tell it to try resuming. If it fails, it will just suspend again and restart the cycle.

Source: https://github.com/NSLS-II/bluesky/blob/master/bluesky/suspenders.py#L113

**Comment by sbillinge** [comment]
Short summary for Tim/Soham:

For now set the SuspendFloor suspender when the RE is instantiated using
the 23ID PV and reasonable threshold values (Dan, were those numbers
reasonable or were you just giving wild numbers as an example?). This
should give the behavior we want for the Tramps so (test it if you
can....you will need a beam dump though!...but) don't do anything more
before we discuss it.

Tim, you can do this as a local edit.

S

On Monday, February 15, 2016, Dan Allan <notifications@github.com> wrote:

> That's probably not enough (or right) for a definitive solution, but that
> behavior does seem to be consistent today.
>
> In that case, type
>
> from bluesky.suspenders import PVSuspendFloor
> PVSuspendFloor(RE, 'PV_HERE', 7.5e-9, resume_thresh=8.3e-9)
>
> in the interactive session, or add it to the IPython profile. Relevant
> section of docs:
> http://nsls-ii.github.io/bluesky/state-machine.html#suspending
>
> Naively, it seems strange to me that we wouldn't be able to find a PV
> upstream of the photon shutter that would let us know when there is a beam
> dump.
>
> 23ID has something set up for this. Assuming that beam dumps are
> experienced more or less uniformly around the ring, you can probably read
> from their value. Quoting from their beamline config:
>
> ring_curr = EpicsSignal('XF:23ID-SR{}I-I', name='ring_curr')
>
> If a long scan is interrupted by a beam dump (as is the case today for
> every attempted measurement) we wouldn't want to redo the whole ramp, and
> unless it freezes at a convenient point near the end/beginning of a tseries
> plan, we need to redefine a scan object, which updates bt.list, which
> changes all indices for the other objects.
>
> I'm not sure what "ScanPlan" does, but if it's built on AbsScanPlan or
> any bluesky step scan plan, a suspension or a user-initiated pause should
> cause it to rewind to the last step, not redo the entire scan. Example:
>
> RE(AbsScanPlan([pe1c], cs700, t1, t2, num_steps), **dict_of_metadata_from_bt)
>
> Question: If we are absent for a beam dump during a long scan, is there an
> easy way to find out what the last image collected was that had counts?
>
> I think we agree that identifying the problem upstream is preferable, but
> there are two alternatives along the lines you suggest:
>
>    1. Add a callback that looks at pe1_stats1_total or pe1_image and, if
>    it sees low counts, calls RE.request_pause(). This would of course
>    *pause*, not suspend, so it would wait for the user before it could
>    resume.
>
> def pause_on_low_counts(name, doc):
>     if 'pe1_stats1_total' not in doc['data']:
>         # this callback is not applicable to this event
>         return
>     total_counts = doc['data']['pe1_stats1_total']
>     if total_counts < THRESH:
>         RE.request_pause()
>
> token = RE.subscribe('event', pause_on_low_counts)# 'token' is an integer you can use to unsubscribe later: RE.unsubscribe(token)
>
>
>    1. Write your own suspender. All of the subtle code is in a base
>    class. Unfortunately, that base class does assume that it is talking to a
>    PV, but it would be easy to remove that part and write an EPICS-less
>    suspender that watches something else -- a file, or a binary flag on the
>    class that is flipped by some other process. Then, use the code above, but
>    instead of calling request_pause, flip a binary flag that tells
>    _should_suspend to start returning True. Wait ten minutes and tell it
>    to try resuming. If it fails, it will just suspend again and restart the
>    cycle.
>
> Source:
> https://github.com/NSLS-II/bluesky/blob/master/bluesky/suspenders.py#L113
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184224710>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by danielballan** [comment]
> Dan, were those numbers reasonable or were you just giving wild numbers as an example?

I took the numbers from Soham's comment [above](https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184074997), which he obtained empirically by watching the CCG BS:WB PV. Those would probably not apply to the ring current PV from 23ID. You would have to watch that PV and glean some representative values yourself. There is no suspender set up at 23ID yet, nothing for us to imitate. They are using it for a different purpose.

**Comment by chiahaoliu** [comment]
I will add `PVSuspendFloor` to startup

**Comment by sbillinge** [comment]
please also make an issue so we remember to put it also into the version of
the startup file in our repo.

Thanks,

S

On Mon, Feb 15, 2016 at 11:26 AM, Timothy Liu <notifications@github.com>
wrote:

> I will add PVSuspendFloor to startup
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184281379>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbanerjee23** [comment]
Hi all, from Mr. Rainer in the Control Room 

>  Here is the PV for the SR Beam Current:
> 
> SR:C03-BI{DCCT:1}I:Real-I
> 
> Enjoy,
> -Rainer

> --
> Rob Rainer
> NSLS II Lead Operator
> 

If I have some time today, I'll try and track down where this is on the 28-ID Launch Page.

**Comment by sbanerjee23** [comment]
From the Launch Page, Beam Current and Lifetime are located under the Machine>Storage Ring window (duh):
![bcpv](https://cloud.githubusercontent.com/assets/7819851/13058574/10fc4028-d3f2-11e5-96cc-b9a0615a1c5f.jpg)

And then below are the PV info for both:
- Beam Current
```
Name: SR:C03-BI{DCCT:1}I:Real-I
State: Connected Running
Value: VDouble[175.19018272125382, 2016/02/15 14:33:45.120]
Display Info: 
Units: mA
Precision: 3
Display_Low: 0.0
Display_High :0.0
Alarm_Low: NaN
Warning_Low: NaN
Warning_High: NaN
Alarm_High: NaN
```
- Life Time

```
Name: SR:C03-BI{DCCT:1}Lifetime-I
State: Connected Running
Value: VDouble[0.0, 2016/02/15 14:33:22.700]
Display Info: 
Units: hour
Precision: 3
Display_Low: 0.0
Display_High :0.0
Alarm_Low: NaN
Warning_Low: NaN
Warning_High: NaN
Alarm_High: NaN
```

Hope that helps.

**Comment by sbillinge** [comment]
Great job !  Now we just need the thresholds.

On Monday, February 15, 2016, Soham Banerjee <notifications@github.com>
wrote:

> From the Launch Page, Beam Current and Lifetime are located under the
> Machine>Storage Ring window (duh):
> [image: bcpv]
> <https://cloud.githubusercontent.com/assets/7819851/13058574/10fc4028-d3f2-11e5-96cc-b9a0615a1c5f.jpg>
>
> And then below are the PV info for both:
>
>    - Beam Current
>
> Name: SR:C03-BI{DCCT:1}I:Real-I
> State: Connected Running
> Value: VDouble[175.19018272125382, 2016/02/15 14:33:45.120]
> Display Info:
> Units: mA
> Precision: 3
> Display_Low: 0.0
> Display_High :0.0
> Alarm_Low: NaN
> Warning_Low: NaN
> Warning_High: NaN
> Alarm_High: NaN
>
>
>    - Life Time
>
> Name: SR:C03-BI{DCCT:1}Lifetime-I
> State: Connected Running
> Value: VDouble[0.0, 2016/02/15 14:33:22.700]
> Display Info:
> Units: hour
> Precision: 3
> Display_Low: 0.0
> Display_High :0.0
> Alarm_Low: NaN
> Warning_Low: NaN
> Warning_High: NaN
> Alarm_High: NaN
>
> Hope that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184359421>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbillinge** [comment]
Btw, these will change with time as the beam current ramps up to 500 mA so
don't hard code it in, make variables that are set during startup.

On Monday, February 15, 2016, Simon Billinge <simon.billinge@gmail.com>
wrote:

> Great job !  Now we just need the thresholds.
>
> On Monday, February 15, 2016, Soham Banerjee <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> From the Launch Page, Beam Current and Lifetime are located under the
>> Machine>Storage Ring window (duh):
>> [image: bcpv]
>> <https://cloud.githubusercontent.com/assets/7819851/13058574/10fc4028-d3f2-11e5-96cc-b9a0615a1c5f.jpg>
>>
>> And then below are the PV info for both:
>>
>>    - Beam Current
>>
>> Name: SR:C03-BI{DCCT:1}I:Real-I
>> State: Connected Running
>> Value: VDouble[175.19018272125382, 2016/02/15 14:33:45.120]
>> Display Info:
>> Units: mA
>> Precision: 3
>> Display_Low: 0.0
>> Display_High :0.0
>> Alarm_Low: NaN
>> Warning_Low: NaN
>> Warning_High: NaN
>> Alarm_High: NaN
>>
>>
>>    - Life Time
>>
>> Name: SR:C03-BI{DCCT:1}Lifetime-I
>> State: Connected Running
>> Value: VDouble[0.0, 2016/02/15 14:33:22.700]
>> Display Info:
>> Units: hour
>> Precision: 3
>> Display_Low: 0.0
>> Display_High :0.0
>> Alarm_Low: NaN
>> Warning_Low: NaN
>> Warning_High: NaN
>> Alarm_High: NaN
>>
>> Hope that helps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xpdAcq/xpdAcq/issues/72#issuecomment-184359421>.
>>
>
>
> --
> Prof. Simon Billinge
> Applied Physics & Applied Mathematics
> Columbia University
> 500 West 120th Street
> Room 200 Mudd, MC 4701
> New York, NY 10027
> Tel: (212)-854-2918 (o) 851-7428 (lab)
>
> Condensed Matter Physics and Materials Science Dept.
> Brookhaven National Laboratory
> P.O. Box 5000
> Upton, NY 11973-5000
> (631)-344-5661
>
> email: sb2896 at columbia dot edu
> home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
>
>

-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
